FROM nelivacn/fat:cuda11.4.3-ubuntu18.04-baseV2024.1

MAINTAINER fat-ga@neliva.com.cn

ADD data.tar /

# docker build -t nelivacn/fat:cuda11.4.3-ubuntu18.04-selftestV2024.1 -f Dockerfile-ubuntu18.04-cuda11.4.3-selftest .
